joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - xv_arm_joint1
    - xv_arm_joint2
    - xv_arm_joint3
    - xv_arm_joint4
    - xv_arm_joint5
    - xv_arm_joint6
    - xv_arm_joint7
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    xv_arm_joint1: {trajectory: 1, goal: 0.01}
    xv_arm_joint2: {trajectory: 1, goal: 0.01}
    xv_arm_joint3: {trajectory: 1, goal: 0.01}
    xv_arm_joint4: {trajectory: 1, goal: 0.01}
    xv_arm_joint5: {trajectory: 1, goal: 0.01}
    xv_arm_joint6: {trajectory: 1, goal: 0.01}
    xv_arm_joint7: {trajectory: 1, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10