gazebo_ros_control:
  pid_gains:
    xv_arm_joint1: {p: 1200.0, i: 5.0, d: 10.0}
    xv_arm_joint2: {p: 1400.0, i: 5.0, d: 10.0}
    xv_arm_joint3: {p: 1200.0, i: 5.0, d: 5.0}
    xv_arm_joint4: {p: 850.0, i: 3.0, d: 5.0}
    xv_arm_joint5: {p: 500.0, i: 3.0, d: 1.0}
    xv_arm_joint6: {p: 500.0, i: 1.0, d: 1.0}
    xv_arm_joint7: {p: 300.0, i: 0.05, d: 1.0}
    drive_joint: {p: 300.0, i: 0.05, d: 1.0}